export const IS_LOGINED = 'IS_LOGINED'
export const POST_CONTENTS = 'POST_CONTENTS'
export const POST_TITLE = 'POST_TITLE'
export const POST_DATE = 'POST_DATE'
export const COMMENT_ITEM_LIST = 'COMMENT_ITEM_LIST'